### PR TITLE
fix: avoid orphaned nodes during setNodes calls

### LINKED ISSUE #68: [persistent-merkle-tree] orphaned nodes after setNodes api
with the current implementation of `setNodes` apis, some nodes created during the rebinding but are not part of either old tree or new tree, and become orphaned. For example if we set new nodes 4x, 5x, 6x, 7x at depth 2 for the tree below

```
                       1
               2              3
      4(4x)   5(5x)    6(6x)    7(7x)
```

after the 1st traversal to node 4, we create parent of node 4x and node 5 (old) but it's not part of the final tree, because when we traverse to node 5, we create a new binding with node 4x and 5x

we can improve the binding by create a new parent of 4x and 5x right at the 1st traversal but it does not resolve the issue because it may happen at parent nodes as well(but it's a nice too have)

This leads to:
- some child nodes are not released to the pool too due to reference count is not 0
- allocated nodes in pool will keep growing in consumer application (lodestar)

### PR DESCRIPTION
**Pull request by twoeths**
**Motivation**
- avoid orphaned nodes during setNodes api

**Description**
- maintain `unfinalized_parents_buf` when moving left
  - if later on it's a right move, mark it as finalized by setting items to `null`
  - otherwise on right move, `unref` it and return to pool
- return nodes to pool if it fails part way
- a lot of unit tests added to make sure there is no orphaned node

Closes #68

### CODE REVIEW

File: src/persistent_merkle_tree/Node.zig [hunk 1]
```diff
@@ -205,6 +205,18 @@ pub const Pool = struct {
         return self.createUnsafe(self.nodes.items(.state));
     }
 
+    /// Returns the number of nodes currently in use (not free)
+    pub fn getNodesInUse(self: *Pool) usize {
```
Comment (twoeths) [inline src/persistent_merkle_tree/Node.zig:209]: this is not supposed for application, it's for tests only where we want to make sure there is no orphaned nodes

File: src/persistent_merkle_tree/Node.zig [hunk 2]
```diff
@@ -697,6 +736,15 @@ pub const Id = enum(u32) {
                 path_lefts[next_d_offset..path_len],
                 path_rights[next_d_offset..path_len],
             );
+
+            // unref prev parents if it's not part of the new tree
+            // can only unref after the rebind
+            for (next_d_offset..path_len) |bit_i| {
+                if (right_move[bit_i] and unfinalized_parents_buf[bit_i] != null) {
+                    pool.unref(unfinalized_parents_buf[bit_i].?);
```
Comment (wemeetagain) [inline src/persistent_merkle_tree/Node.zig:744]: We want one of two possible outcomes:
- if there's no error, then both the old and new tree exist (and all temporary/orphaned nodes are freed)
- if there's an error, then only the old tree exists (all newly created nodes are freed)

How does this work in these cases?
- In the non-error case, I suppose the "unfinalized parents" that are being unrefed are these temporary/orphaned nodes
- if an error is hit (eg run out of memory) only after several indices have been rebound?
- if an error is hit immediately? it looks like the root node might get (incorrectly) unrefed?
